---
title: nickal.es
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  shirts:
    title: Shirt Designs
    output: true
  uploads:
    title: Uploads
    output: true
  portfolio:
    title: portfolio
    output: true
email: bransnic000@gmail.com
description: hey there.
baseurl: 
url: nickal.es
twitter_username: nickalesgb
github_username: nickales
markdown: kramdown
highlighter: rouge
paginate: 15
paginate_path: "/blog/page:num/"
