---
title: nickal.es
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  t-shirt-designs:
    title: T-shirt designs
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
